[package]
name = "crs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = "2.8.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
serialport = "4.2.1"
