name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:


  build-macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd "Rust Middleware" && cargo build --release --verbose
    - name: Run tests
      run: cd "Rust Middleware" && cargo test --verbose
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "macOS"
        path: "Rust Middleware/target/*"
