name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:


  build-macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
#    - name: Build x86_x64
#      run: cd "Rust Middleware" && cargo build --release --verbose
    - name: Build Apple Silicon
      run: cd "Rust Middleware" && rustup target add aarch64-apple-darwin && cargo build --release --target aarch64-apple-darwin --verbose
#    - name: Run tests
#      run: cd "Rust Middleware" && cargo test --verbose
    - name: Prepare upload
      run: mkdir "build" && mv "Rust Middleware/target/aarch64-apple-darwin/release/crs" "build/"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "macOS"
        path: "build/*"
