name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd "Rust Middleware" && cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Prepare Upload
      run: mkdir "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/build" && mv "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/Rust Middleware/target/release/crs*" "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/build/"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Builds"
        path: "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/build/*"
