name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Libs
      run: sudo apt-get install libudev-dev
    - name: Build
      run: cd "Rust Middleware" && cargo build --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Built (Ubuntu)"
        # A file, directory or wildcard pattern that describes what to upload
        path: "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/Rust Middleware/target/debug/crs"
