name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: sudo apt-get install libudev-dev && rustup target add x86_64-pc-windows-gnu && sudo apt-get install x86_64-w64-mingw32-gcc
    - name: Build Linux
      run: cd "Rust Middleware" && cargo build --release --verbose
    - name: Build Windows
      run: cd "Rust Middleware" && cargo build --release --target x86_64-pc-windows-gnu --verbose
    - name: Prepare Upload
      run: mv "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/Rust Middleware/target/release/crs" "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/build/crs" && mv "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/Rust Middleware/target/x86_64-pc-windows-gnu/release/crs.exe" "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/build/crs.exe"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Builds"
        path: "/home/runner/work/Calliope-Radio-Scanner/Calliope-Radio-Scanner/build/*"
